# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-28 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
