# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-28 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_app', '0002_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowManager',
        ),
    ]
